export const QUERY_KEYS = {
  USERS: "users",
  TICKETS: "tickets",
  ACTORS: "actors",
  MOVIES: "movies",
  MOVIE: "movie",
  SCHEDULES: "schedules",
  MOVIE_SCHEDULE: "movie-schedule",
  LANGUAGES: "languages",
  GENRES: "genres",
  CINEMA: "string",
  ROOM: "rooms",
  SEARCH_HISTORY: "search-history",
  MOVIE_SEARCH: "movie-search",
  SEATS: "seats",
  SHOWING_MOVIE: "showing-movie",
  SEATS_ROOM: "seats-room",
  CINEMA_SCHEDULE: "cinema-schedule",
};
