export * from "./authRouter"
export * from "./castRouter";
export * from "./genreRouter";
export * from "./languageRouter";
export * from "./movieRouter";
export * from "./paymentRouter";
export * from "./s3Router";
export * from "./schedulesRouter";
export * from "./userRouter";
