export * from "./authRouter"
export * from "./castRouter";
export * from "./cinemaRouter";
export * from "./genreRouter";
export * from "./languageRouter";
export * from "./movieRouter";
export * from "./paymentRouter";
export * from "./roomRouter";
export * from "./s3Router";
export * from "./schedulesRouter";
export * from "./seatRouter";
export * from "./userRouter";
