export * from "./authController";
export * from "./castController";
export * from "./errorController";
export * from "./genreController";
export * from "./languagesController";
export * from "./movieController";
export * from "./s3Controller";
export * from "./scheduleController";
export * from "./userController";