-- AlterTable
ALTER TABLE "Movie" ALTER COLUMN "Price" SET DATA TYPE DECIMAL(9,2),
ALTER COLUMN "VoteAverage" SET DATA TYPE DECIMAL(4,2);

-- AlterTable
ALTER TABLE "Reservation" ALTER COLUMN "TotalPrice" SET DATA TYPE DECIMAL(9,2);
